ALTER TABLE users ADD COLUMN bank_name VARCHAR(100) DEFAULT '' AFTER email;
ALTER TABLE users ADD COLUMN account_number VARCHAR(50) DEFAULT '' AFTER bank_name;
ALTER TABLE users ADD COLUMN ifsc VARCHAR(50) DEFAULT '' AFTER account_number;
ALTER TABLE users ADD COLUMN upi_id VARCHAR(100) DEFAULT '' AFTER ifsc;
